sudo: required
dist: trusty
language: node_js
node_js:
  - '7'

install:
  - npm install

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: 
 - npm test
